// tailwind.config.mjs
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    borderRadius: {
      DEFAULT: '0px',
      none: '0px',
      sm: '0px',
      md: '0px',
      lg: '0px',
      xl: '0px',
      '2xl': '0px',
      '3xl': '0px',
      card: '0px',
      full: '9999px',
    },
    extend: {
      colors: {
        // Stitch Editorial Curator color system
        'primary':                  '#000000',
        'primary-container':        '#001b3d',
        'on-primary':               '#ffffff',
        'on-primary-container':     '#6684b9',
        'primary-fixed':            '#d6e3ff',
        'primary-fixed-dim':        '#a9c7ff',
        'on-primary-fixed':         '#001b3d',
        'on-primary-fixed-variant': '#264778',
        'secondary':                '#ae3100',
        'secondary-container':      '#fe6431',
        'on-secondary':             '#ffffff',
        'on-secondary-container':   '#5b1500',
        'secondary-fixed':          '#ffdbd0',
        'secondary-fixed-dim':      '#ffb59f',
        'on-secondary-fixed':       '#3a0a00',
        'on-secondary-fixed-variant':'#852400',
        'tertiary':                 '#000000',
        'tertiary-container':       '#001c3b',
        'on-tertiary':              '#ffffff',
        'on-tertiary-container':    '#6e85aa',
        'tertiary-fixed':           '#d5e3ff',
        'tertiary-fixed-dim':       '#b0c8f0',
        'on-tertiary-fixed':        '#001c3b',
        'on-tertiary-fixed-variant':'#30486a',
        'surface':                  '#f9f9f9',
        'surface-bright':           '#f9f9f9',
        'surface-dim':              '#dadada',
        'surface-variant':          '#e2e2e2',
        'surface-tint':             '#405f91',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#f3f3f3',
        'surface-container':        '#eeeeee',
        'surface-container-high':   '#e8e8e8',
        'surface-container-highest':'#e2e2e2',
        'on-surface':               '#1a1c1c',
        'on-surface-variant':       '#44474c',
        'on-background':            '#1a1c1c',
        'background':               '#f9f9f9',
        'inverse-surface':          '#2f3131',
        'inverse-on-surface':       '#f0f1f1',
        'inverse-primary':          '#a9c7ff',
        'outline':                  '#74777d',
        'outline-variant':          '#c4c6cc',
        'error':                    '#ba1a1a',
        'error-container':          '#ffdad6',
        'on-error':                 '#ffffff',
        'on-error-container':       '#93000a',
        // Legacy aliases kept for non-homepage pages
        'text-primary':             '#1a1c1c',
        'text-secondary':           '#44474c',
        'bg-primary':               '#ffffff',
        'bg-secondary':             '#f3f3f3',
        'border-color':             '#c4c6cc',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body:     ['Manrope', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
        // legacy alias
        sans: ['Manrope', 'Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
      },
      boxShadow: {
        light:  '0 2px 40px rgba(26,28,28,0.06)',
        medium: '0 4px 40px rgba(26,28,28,0.08)',
        heavy:  '0 8px 40px rgba(26,28,28,0.12)',
      },
    },
  },
  plugins: [],
};
